server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/csylovewwj/springcloud_config.git
          search-paths:
            - SpringCloud3_day_Config
          default-label: dev  # 可以写可以不写！！
          password: csy123654
          username: 13674971648 # 如果是公共仓库，则可以不用输入账号密码，如果是私有的，则需要输入账号密码


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  # 集群版